name: Setup conda env with numpy and pytest
on: [push]
jobs:
  conda-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'windows-latest', 'ubuntu-latest' ]
        python-version: [ '3.9', '3.10' ]
    name: Test conda-${{ matrix.python-version }}-${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          conda-version: 4.11
      - name: Install dependencies
        run: |
          conda install numpy pytest